esphome:
  name: fancontrol
  platform: ESP8266
  board: d1_mini_lite
  libraries:
    - SPI
    - Ticker

external_components:
  - source: 
      type: git
      url: https://github.com/CoMPaTech/esphome_ct
      ref: dev2
    # refresh: 3600s # only set this briefly otherwise it just refreshes daily, see https://esphome.io/components/external_components#external-components-refresh for setting refresh too low

fan:
  - platform: "cc1101"
    speed_count: 3
    name: "Mechanical Fan"
    data_pin: D1
    map_off_to_zero: True
    id: mech_fan

button:
  - platform: template
    name: "Send join command"
    on_press:
      then:
        - component.cc1101.mech_fan:
            call: send_other_command
            command: 0
  - platform: template
    name: "Run Timer for 10 Minutes"
    on_press:
      then:
        - component.cc1101.mech_fan:
            call: send_other_command
            command: 1
